# Generated by Django 2.2.4 on 2019-08-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='StdID',
            new_name='Search',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Score',
        ),
    ]
